disabled_rules:
  - identifier_name
  - line_length
  - todo
  - trailing_comma
  - trailing_newline
  - vertical_whitespace
opt_in_rules:
  - closure_end_indentation
  - file_header
excluded:
  - Carthage
  - fastlane
  - Pods
  - public
  - scripts
  - vendor
file_header:
  forbidden_pattern: .
  severity: error
