name: XAppRecipe
options:
  deploymentLanguage: Japan
  postGenCommand: pod install
settings:
  PRODUCT_BUNDLE_IDENTIFIER: work.shion.xapprecipe
targets:
  App:
    deploymentTarget: "12.0"
    platform: iOS
    sources:
      - App
      - path: public
        type: folder
    type: application
