name: XAppRecipe
options:
  deploymentLanguage: Japan
settings:
  PRODUCT_BUNDLE_IDENTIFIER: work.shion.xapprecipe
targetTemplates:
  appbase:
    platform: iOS
    preBuildScripts:
      - path: ../scripts/lint.sh
        name: Run Lint
    postBuildScripts:
      - path: ../scripts/format.sh
        name: Run Format
    sources:
      - App
      - path: public
        type: folder
    type: application


targets:
  App:
    templates:
      - appbase
    deploymentTarget: "12.0"
  AppPreview:
    templates:
      - appbase
    deploymentTarget: "13.0"
    sources:
      - AppPreview
  AppTests:
    dependencies:
      - target: App
    platform: iOS
    settings:
      INFOPLIST_FILE: AppTests/info.plist
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/App.app/App
    sources:
      - AppTests
    type: bundle.unit-test
