name: XAppRecipe
options:
  deploymentLanguage: Japan
  postGenCommand: pod install
settings:
  PRODUCT_BUNDLE_IDENTIFIER: work.shion.xapprecipe
targets:
  App:
    deploymentTarget: "12.0"
    platform: iOS
    sources:
      - App
      - path: public
        type: folder
    type: application
  AppPreview:
    deploymentTarget: "13.0"
    platform: iOS
    sources:
      - App
      - path: public
        type: folder
      - AppPreview
    type: application
  AppTests:
    dependencies:
      - target: App
    platform: iOS
    settings:
      INFOPLIST_FILE: AppTests/info.plist
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/App.app/App
    sources:
      - AppTests
    type: bundle.unit-test
