name: XAppRecipe
options:
  deploymentLanguage: Japan
  postGenCommand: pod install
targets:
  App:
    deploymentTarget: "12.0"
    platform: iOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: work.shion.xapprecipe
    sources:
      - App
      - path: public
        type: folder
    type: application
